unix/README.md

It helps having the dependencies listed before the actual install instructions, so that one doesn't have to have the configure step fail multiple times before hitting each dependency.

Trivial update to README.md

---

source/parser/parser_expressions.cpp

Enables users to determine the x,y,z ranges, returned as a vector, for
density_file based pigments matching a similar function for image maps.

Adding df3, density_file query range support to max_extent.

---

distribution/scenes/templates/height_field_and_HF_macros/30_HF_Sphere_macro.txt

Reported by omniverse on povray.documentation.inbuilt.
See: 
http://news.povray.org/povray.documentation.inbuilt/message/%3Cweb.57ede719b90612ffb1933f770%40news.povray.org%3E/#%3Cweb.57ede719b90612ffb1933f770%40news.povray.org%3E

Adding missing close paren in 30_HF_Sphere_macro.txt

---

source/parser/parser_expressions.cpp

When expecting a 4D vector, the parser would erroneously treat a 3D vector as if it had 4 components, despite only setting 3 (so that the fourth component would retain whatever value was in that memory location).  (More precisely, Parse_Num_Factor would fail to update `*Terms` when parsing a 3D vector token if `*Terms>3`.)  This would cause, e.g., `julia_fractal{2/9*x}` to get parsed as if one had written `julia_fractal{2/9*<1,0,0,9>}`.
This fixes that issue.  (I also removed a nearby comment that no longer makes much sense.)

Fix 4D vector parsing anomaly

---

source/parser/parser_materials.cpp

Fixing an issue I hit some years ago. See attached test scene file with both function -> pattern and function -> pigment variants for all tiling patterns.  
[tilingPatternsAsIsosurfacesTest.pov.txt](https://github.com/POV-Ray/povray/files/490796/tilingPatternsAsIsosurfacesTest.pov.txt)

Fixing tiling pattern use in functions.

---

source/base/fileinputoutput.cpp

This fixes an (silent) automatic failure when attempting to append to files.

Fix file append bug

---

source/base/image/hdr.cpp

An invalid comparison of IStream to bool in hdr.cpp prevented compilation.  This fixes that.

Minor fix to hdr.cpp

---

source/parser/parser_materials.cpp

function { pattern { potential { Blob00 } threshold on } } use was
causing a scene parse error.
An example scene file for the problem fixed is attached. 
[fixPotentialThresholdInFnct.pov.txt](https://github.com/POV-Ray/povray/files/485560/fixPotentialThresholdInFnct.pov.txt)

Fixing potential pattern threshold keyword use in function.

---

.gitignore
unix/prebuild.sh

Adds unix/config/compile (created by automake) to .gitignore and adds it to the cleanup list in unix/prebuild.sh.

Ignore + cleanup unix/config/compile

---

source/core/math/polynomialsolver.cpp

See:
http://news.povray.org/povray.programming/thread/%3Cweb.580874a6f9e539ccf4af9d600%40news.povray.org%3E/
Likely Christoph this change already done in your local code, but this pull
req in place to be sure we don't forget it. Jerome has already updated his hg-povray.

Fix placement of break statement in Solve_Polynomial.

---

source/core/shape/cone.cpp
source/core/shape/cone.h

Note I flipped the UV mapping in V as it looked upside down to the usual
POV-Ray UV mapping. Related comments in the code.
Attaching a test scene file: 
[mappings.pov.txt](https://github.com/POV-Ray/povray/files/550409/mappings.pov.txt)

Port of JG uv_mapping for cylinder and cone.

---

source/core/shape/lemon.cpp

The UV mapping orientation for the originally implemented lemon was upside down to the usual mapping.
See :
http://news.povray.org/povray.beta-test/thread/%3C580cd1a7%241%40news.povray.org%3E/
and attached scene file.
[mappings.pov.txt](https://github.com/POV-Ray/povray/files/550286/mappings.pov.txt)

Flipping uv_mapping of lemon in V to usual orientation.

---

source/parser/parser.h
source/parser/parser_expressions.cpp

This fixes the bug reported in http://news.povray.org/3c4bb31d$1@news.povray.org.  (This also does some general cleanup of source/parser/parser_expressions.cpp.)
(Promotion was occurring before it was needed, causing (sub-)expressions to produce different results depending on context.  For instance, floats were being directly promoted by `Parse_Num_Factor`, causing, e.g.: `<1,0,0>+1*t` to parse as `<1,0,0>+<1,1,1>*t` and thence `<1,0,0>+<1,1,1,0>*<0,0,0,1>` (the bug reported).  This has been fixed by removing uses of `*Terms` as an input parameter to functions (but still using it as an output parameter).)

Fix promotion bug

---

unix/disp.h
unix/disp_sdl.cpp
vfe/unix/unixconsole.cpp

The end render message:  Press a key or click the display to continue...
for unix versions has long been inaccurate because you cannot click any
key, but rather only a few specific ones.  Pauses with 'p' also gave no
clue in the paused message to use 'p' to continue.  Update somewhat
complicated for being only text message changes due no-display runs or
compiles without SDL installed - and so no-display - not picking up
general key press events.

Improving unix console messages with SDL display use.

---

source/frontend/processrenderoptions.cpp
unix/povray.1

Updating our unix man page to be current with recent 3.71 master.
Also small typo in processrenderoptions.cpp.

[ci skip] Updating the unix man page. Small typo.

---

source/backend/control/scene.cpp
source/base/configbase.h
source/frontend/renderfrontend.cpp

Related to ussues #59 and #180. When no bounding threshold is specified
centralizes centralizes the setting and reporting of the bounding
threshold to 3. Further, restores the clamping of values to 1+ which
existed in 3.6.
In deciding to apply this fix to the 3.71 release, this change was
re-based onto release/v3.7.1 and a new pull request create replacing
request #181 against the master branch.

Fixing issues with bounding threshold option.

---

source/backend/configbackend.h
source/backend/support/task.cpp
unix/povconfig/syspovconfigbackend.h

Thread stack size defaulting refined. New adjustments for
64 bit compiles vs 32 bit and linux needing a larger stack size
than windows for one recent pre 371 regression.
New sub macros POV_COMPILE64 and POV_THREAD_STACK_SIZE_DEFAULTED
created in support of POV_THREAD_STACK_SIZE macro. See Doxygen
comments in code for more detail.
See newsgroup thread: 
http://news.povray.org/povray.beta-test/message/%3C589458a6%40news.povray.org%3E/#%3C589458a6%40news.povray.org%3E
A small hmm.cpp file attached which was used for test the macros and various overrides on my Ubuntu machine:  
[hmm.cpp.txt](https://github.com/POV-Ray/povray/files/753195/hmm.cpp.txt)

Adding POV_THREAD_STACK_SIZE macro.

---

source/backend/control/scene.cpp
source/backend/povray.cpp
source/backend/scene/view.cpp

Fixes Dick Balaska's seg fault as reported in beta-test newsgroup on
February 12, 2017. In particular we are extending the
POV_THREAD_STACK_SIZE macro mechanism to all NewBoostThread
calls.
Ref: 
http://news.povray.org/povray.beta-test/thread/%3C58a1e32f%241%40news.povray.org%3E/
Dick's test data as zip: 
[ttcrash.zip](https://github.com/POV-Ray/povray/files/774149/ttcrash.zip)

Fixing thread stack size overrun crash.

---

source/parser/parser.cpp

Relates to github issue #60 and merged pull request #62.
See too the newsgroup thread at:
http://news.povray.org/povray.advanced-users/thread/%3C58de4765%241%40news.povray.org%3E/

Relaxing Parse_Lathe point checking for versions <=3.7

---

source/backend/render/tracetask.cpp

Web searches turned up evidence the existing code has the best
performance for Microsoft Visual C++, but performance is awful for g++
and clang compared to sampled.assign method.
g++ (5.4.0) +a0.05 +am2 +r5 +w1800 +H1200 complete render
(threads==cores) is 23% slower with iterator method.
clang (3.8.0-2) with AA above is 28% slower using iterator.

Improving AA performance for non MSVC compilers.

---

platform/x86/avxportable.cpp
platform/x86/avxportable.h
platform/x86/cpuid.cpp
platform/x86/cpuid.h
platform/x86/optimizednoise.h
windows/povconfig/syspovconfig_msvc.h
windows/pvengine.cpp
windows/vs2015/povplatform.vcxproj
windows/vs2015/povplatform.vcxproj.filters

1) Added new noise implementation "AVXPortable" which is simply PortableNoise compiled separately with compiler AVX flags.
2) Changed the noise code selection based on CPU vendor because the existing AVX and AVX2FMA3 implementations lower performance on non-Intel CPUs compared to the new AVXPortable or existing portable (non-AVX) noise functions.

Add AVXPortable and changed noise code selection

---

source/core/lighting/photons.cpp

While gains vary, anything run with photons was 0.5-2% faster. Scenes like optics.pov show the most gains at 10-12% faster.
-----------
Some data for performance/gatherPhotonsRec  (threads==cores)
```
balcony.pov (no radiosity) 
+W1200 +H900 +A0.1 +am2 +r3 +wt2 -D -P
-----------
Number of photons shot:           21470
Surface photons stored:           26871
Gather function called:        10218658
96.38user 0.05system 0:49.55elapsed
95.65user 0.05system 0:49.15elapsed
95.77user 0.03system 0:49.25elapsed
95.93
Number of photons shot:           21470
Surface photons stored:           26871
Gather function called:        10218074(1)
95.15user 0.07system 0:48.99elapsed
94.52user 0.06system 0:48.62elapsed
94.87user 0.06system 0:48.75elapsed
94.85                               -1.13%
(1) - …
```

Improving performance of gatherPhotonsRec function.

---

source/core/material/texture.h

The FRAND() macro was gone from the code on the initial import of the
code base to git/github.
There are still comments in photons.cpp which reference FRAND().
I'd argue they should be deleted too at this point, but this commit
doesn't do that bit.

[ci skip] Removing comment related to long gone FRAND() macro.

---

source/backend/parser/parsestr.cpp
source/backend/parser/parstxtr.cpp
source/backend/pattern/pattern.cpp
source/backend/render/trace.cpp
source/base/image/hdr.cpp
source/base/povmscpp.h
source/frontend/renderfrontend.cpp
source/frontend/shelloutprocessing.cpp
source/frontend/simplefrontend.h

Minor code modifications to eliminate compile errors in `base/image/hdr.cpp` reported for GNU g++ 6.3.1.
Also cleaned up some clang 4.2 compiler warnings along the way.

Fix compatibility with GCC 6.x

---

unix/prebuild.sh

when linking binaries with g++, order of input files
influences ordering of functions in the output
See https://reproducible-builds.org/ for why this matters.

Make build reproducible

---

source/core/material/texture.cpp
source/parser/parser.cpp
source/parser/parser_tokenizer.cpp

When version is set as the first statement of the scene or via option, and the version is 3.8 or more, the default ambient is 0 instead of the previous 0.1 which has problem with the gamma handling.

Default ambient for 3.8 and above

---

source/core/shape/ovus.cpp
source/core/shape/ovus.h
source/parser/parser.cpp

* allow the center of the top sphere to not be on the top of the bottom sphere (via "distance xxx")"
* allow the radius of the torus spindle to be manually specified (via "radius xxx")
* allow precision of the root solver to be tuned ( via "precision xxx")
And change of UV-Mapping to be similar to the uv-mapping of cone & cylinder

Extension of ovus to:

---

.gitignore

Notes. The new 'ar-lib' file link into the automake install showed up when I updated to the latest 3.8, but might be due automake itself or automake as now called. The ar-lib program is one of those I had to specially download when playing with link time optimization.

[ci skip] Adding /unix/config/ar-lib to .gitignore.

---

source/base/configbase.h
source/base/fileinputoutput.cpp
source/base/messenger.cpp
source/base/stringutilities.cpp
source/base/textstream.cpp
source/base/textstreambuffer.cpp
source/frontend/processoptions.cpp
source/parser/parser.cpp
source/parser/parser_strings.cpp
unix/configure.ac
unix/povconfig/syspovconfig.h
vfe/unix/vfeplatform.cpp
vfe/vfe.cpp
vfe/vfecontrol.cpp
windows/povconfig/syspovconfig.h
windows/pvtext.cpp

Also replace `FILE_NAME_LENGTH` macro along the way in hope to clarify the code, and eliminate `MAX_PATH` from all but the Windows-specific code.

Clean up use of `snprintf`/`vsnprintf` to use C++11 standard functions.

---

source/core/math/hypercomplex.cpp

a small typo, a huge impact on rendered fractal (where .y component was
used also as .z, ignoring the provided .z )

Correct (historical) typo for Julia fractal with hypercomplex

---

source/backend/povray.cpp
source/base/image/openexr.cpp
unix/config/ax_check_openexr.m4
windows/vs10/povbase.vcxproj

Changes to support OpenEXR 3,0

Changes to support OpenEXR 3.0.

---

source/backend/lighting/radiosity.cpp

This pull request duplicates an old fix already applied to the 3.7.1 branch, fixing a crash in `radiosity.cpp` when mosaic pretrace is enabled (originally tracked on FlySpray as FS313 and recently reported again on the `povray.bugreports` newsgroup).

Fix crash in radiosity.cpp related to mosaic preview.

---

source/parser/parser_expressions.cpp

When used in `spline { SPLINE_IDENTIFIER ... }` without explicitly specifying spline type again, the new copy would get demoted to `linear_spline` (see newsgroup post `<XnsAD687938A665Aseed7@news.povray.org>`, 2021-07-15, povray.beta-test, "spline in, out array bug").

Fix splines becoming linear when duplicated.

---

source/parser/parser_expressions.cpp

To work around Boost's msec-precision UTC timer erroneously reporting local time instead of UTC on some systems, we're now also probing the sec-precision UTC timer, which should be more reliable in terms of time zone: The rounded difference between the two should be able to give us the time zone offset (if any) in the msec-precision timer, which we then compensate for accordingly.

Fix for #432.

---

source/backend/control/scene.cpp
source/core/scene/scenedata.h
source/parser/parser.cpp

Precision of `Declare` INI setting was erroneously truncated to 6 digits. Reverted back to 7 digits, matching v3.6 behavior.

Partial fix for #428.

---

README.md
source/frontend/configfrontend.h
source/frontend/renderfrontend.cpp
source/frontend/shelloutprocessing.cpp
source/frontend/shelloutprocessing.h
source/parser/fncode.cpp
source/parser/parser.cpp
source/parser/parser_expressions.cpp
source/parser/parser_functions.cpp
windows/pvbitmap.cpp

Found via `codespell -q 3 -S "./libraries" -L ans,feld,medias,nd,pary,pres,sie,thn,writen`

Fix various typos

---

distribution/scenes/advanced/pawns.pov

Two improvements to the `pawns.pov` demo scene:
* Fix z-fighting (speckling) on the chessboard caused by overlapping boxes
* Correcting colors back to their original values, which had been lost when the behavior of `filter` changed in 3.5.
Before:
After:

Fixes to scenes/advanced/pawns.pov
